name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build Docker image
      run: make build

    - name: Push Docker image
      run: make push
      env:
        DOCKER_ID_USER: ${{ secrets.DOCKER_NAME }}
        IMAGE_NAME: container_demo