name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Set up Environment Variables
        run: |
          echo "DOCKER_NAME=${{ secrets.DOCKER_NAME }}" >> $GITHUB_ENV
          echo "SQL_HTTP_PATH=${{ secrets.DOCKER_ACCESS_TOKEN }}" >> $GITHUB_ENV
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
      - name: deploy
        run: make deploy